/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import model.model_cli;

/**
 *
 * @author home
 */
public class ClientItem extends javax.swing.JPanel {

    /**
     * Creates new form model_cli
     */
    
    private boolean selected;
    public ClientItem(model_cli data,int id) {
        initComponents();
        
        if(data.isIsCreditor()){
            if(data.getResteAPayer() <= 0){
                setBackground(Color.decode("#00FF00"));
            }else{
                setBackground(Color.decode("#FF0000"));
            }
        }else{
            setBackground(Color.decode("#333333"));
        }
        nom.setText(data.getNom());
        numero.setText(id+"");
    }
    
    public void setSelected(boolean selected){
        this.selected = selected;
        repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numero = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        suppr = new javax.swing.JLabel();
        view = new javax.swing.JLabel();

        numero.setForeground(new java.awt.Color(255, 255, 255));
        numero.setText("num");

        nom.setForeground(new java.awt.Color(255, 255, 255));
        nom.setText("nom");

        suppr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/img/icon/i6.png"))); // NOI18N

        view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/img/icon/i5.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numero)
                .addGap(18, 18, 18)
                .addComponent(nom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suppr)
                .addGap(18, 18, 18)
                .addComponent(view)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(suppr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero)
                    .addComponent(nom))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void paintComponent(Graphics grph){
        if(selected){
            Graphics2D g2 = (Graphics2D) grph;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
            if(selected){
                nom.setForeground(Color.decode("#0000FF"));
                numero.setForeground(Color.decode("#0000FF"));
            }else{
                nom.setForeground(Color.decode("#FFFFF"));
                numero.setForeground(Color.decode("#FFFFF"));
            }
            g2.fillRect(0,0, getWidth(),getHeight());
        }
        super.paintComponent(grph);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nom;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel suppr;
    private javax.swing.JLabel view;
    // End of variables declaration//GEN-END:variables
}
