/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import model.Model_menu;

/**
 *
 * @author home
 */
public class menuItem extends javax.swing.JPanel {

    /**
     * @param over the over to set
     */

    private boolean selected;
    private boolean over;
    
    public menuItem(Model_menu data) {
        initComponents();
        setOpaque(false);
        if(data.getType() == Model_menu.menu_type.MENU){
            licon.setIcon(data.toIcon());
            lname.setText(data.getName());
        }else if(data.getType() == Model_menu.menu_type.TITLE){
            licon.setText(data.getName());
            licon.setFont(new Font("sansserif",1,12));
            lname.setVisible(false);
        }else{
            lname.setText("");
        }
            
    }
    
    public void setSelected(boolean selected){
        this.selected = selected;
        repaint();
    }
    
    public void setOver(boolean over) {
        this.over = over;
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        licon = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();

        licon.setBackground(new java.awt.Color(255, 255, 255));
        licon.setForeground(new java.awt.Color(255, 255, 255));

        lname.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setText("Nom item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(licon)
                .addGap(18, 18, 18)
                .addComponent(lname)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(licon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lname, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics grph){
        if(selected || over){
            Graphics2D g2 = (Graphics2D) grph;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
            if(selected){
                g2.setColor(new Color(10, 40, 101));
            }else{
                g2.setColor(new Color(198, 208, 251,20));
            }
            g2.fillRect(0,0, getWidth(),getHeight());
        }
        super.paintComponent(grph);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel licon;
    private javax.swing.JLabel lname;
    // End of variables declaration//GEN-END:variables
}
