/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import model.marchandise;

/**
 *
 * @author home
 */
public class renduMarchandise extends javax.swing.JPanel {

    /**
     * Creates new form renduMarchandise
     */
    public renduMarchandise(marchandise data) {
        initComponents();
    }
    public renduMarchandise(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        style1 = new swing.style();
        nom = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();
        backPrix = new swing.PanelBorder();
        prix = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(245, 180));

        nom.setFont(new java.awt.Font("Sitka Small", 0, 15)); // NOI18N
        nom.setForeground(new java.awt.Color(51, 51, 51));
        nom.setText("nom");

        stock.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        stock.setForeground(new java.awt.Color(51, 51, 51));
        stock.setText("En Stock : 0");

        backPrix.setBackground(new java.awt.Color(255, 255, 255));

        prix.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        prix.setForeground(new java.awt.Color(102, 102, 102));
        prix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prix.setText("1000Ar");

        javax.swing.GroupLayout backPrixLayout = new javax.swing.GroupLayout(backPrix);
        backPrix.setLayout(backPrixLayout);
        backPrixLayout.setHorizontalGroup(
            backPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPrixLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prix, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );
        backPrixLayout.setVerticalGroup(
            backPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPrixLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout style1Layout = new javax.swing.GroupLayout(style1);
        style1.setLayout(style1Layout);
        style1Layout.setHorizontalGroup(
            style1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, style1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(style1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(style1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stock)
                    .addComponent(nom))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        style1Layout.setVerticalGroup(
            style1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(style1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(nom)
                .addGap(18, 18, 18)
                .addComponent(stock)
                .addGap(9, 9, 9)
                .addComponent(backPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(style1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(style1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.PanelBorder backPrix;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel prix;
    private javax.swing.JLabel stock;
    private swing.style style1;
    // End of variables declaration//GEN-END:variables
}
