/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Component;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author home
 */
public class Header extends javax.swing.JPanel {

    /**
     * Creates new form Header
     */
    
    Date date;
    String dateHeure;
    
    public Header() {
        date = new Date();
        initComponents();
        setOpaque(false);
        timeNow();
        exitBTN();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchText1 = new swing.searchText();
        exit = new javax.swing.JLabel();
        resize = new javax.swing.JLabel();
        dateH = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(680, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/img/icon/i1.png"))); // NOI18N

        exit.setBackground(new java.awt.Color(255, 102, 153));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/img/icon/i4.png"))); // NOI18N
        exit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        resize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/img/icon/i2.png"))); // NOI18N
        resize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        dateH.setForeground(new java.awt.Color(153, 153, 153));
        dateH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateH.setText("dd/MM/yyyy   HH:mm:ss");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchText1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resize, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(resize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dateH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


        @Override
    public void paintComponent(Graphics grph){
        Graphics2D g2 = (Graphics2D) grph;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(250, 248,255));
        g2.fillRoundRect(0,0, getWidth(),getHeight(),15,15);
        g2.fillRect(0, 0, 25, getHeight());
        g2.fillRect(getWidth() - 25, getHeight() - 25, getWidth(), getHeight()); 
        
        super.paintComponent(grph);
    }
    
    public void timeNow(){
        System.out.println(date.getTime());
        Timer time = new Timer(1000, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                mettreAJourDateHeure();
            }
        });
        time.start();
    }
    private void mettreAJourDateHeure() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy  HH:mm:ss");
        Date maintenant = new Date();
        String dateHeure = sdf.format(maintenant);
        dateH.setText(dateHeure);
    }
    
    private void exitBTN(){
        exit.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent me){
                //close app
                if(SwingUtilities.isLeftMouseButton(me)) System.exit(0);
            }
        });
    }
    
    private boolean full = false;
    
    public void resizeBTN(JFrame fm){
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();
        resize.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent me) {
                if(SwingUtilities.isLeftMouseButton(me)){  
                    if(!full){
                        fm.dispose();
                        gd.setFullScreenWindow(fm);
                        full = true;
                    }else{
                        fm.dispose();
                        gd.setFullScreenWindow(null);
                        fm.setSize(1150,575);
                        fm.setLocationRelativeTo(null);
                        fm.setVisible(true);
                        full = false;
                    }
                }
            }
        });
    }
    

    public swing.searchText getRenderSearchBar(){ return this.searchText1;}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateH;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel resize;
    private swing.searchText searchText1;
    // End of variables declaration//GEN-END:variables
}
