/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Component;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;
import model.Model_menu;

/**
 *
 * @author home
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    
    private EventMenuSelected event;
    
    public void addEventMenuSelected(EventMenuSelected e){
        this.event = e;
        listMenu1.addEventMenuSelected(e);
    }
    
    public Menu() {
        initComponents();
        setOpaque(false);
        listMenu1.setOpaque(false);
        init();
    }
    
    private void init(){
        listMenu1.addItem(new Model_menu("","Gestion des ventes", Model_menu.menu_type.TITLE));
        
        listMenu1.addItem(new Model_menu("g21","Point de vente", Model_menu.menu_type.MENU));
        listMenu1.addItem(new Model_menu("g23","Gestion des clients", Model_menu.menu_type.MENU));
        
        listMenu1.addItem(new Model_menu("","",Model_menu.menu_type.EMPTY));
        listMenu1.addItem(new Model_menu("","Gestion des achats", Model_menu.menu_type.TITLE));
        
        listMenu1.addItem(new Model_menu("g22","Faire un ravitaillement", Model_menu.menu_type.MENU));
        
        listMenu1.addItem(new Model_menu("","",Model_menu.menu_type.EMPTY));
        listMenu1.addItem(new Model_menu("","Gestion des stocks", Model_menu.menu_type.TITLE));
        
        listMenu1.addItem(new Model_menu("g27","Gestion des articles", Model_menu.menu_type.MENU));
        listMenu1.addItem(new Model_menu("g25","Gestion des inventaires", Model_menu.menu_type.MENU)); 
        listMenu1.addItem(new Model_menu("g24","Gestion des fournisseurs", Model_menu.menu_type.MENU));
       
    }
    
    private int x;
    private int y;
    
    public void initMoving(JFrame fram){
        TitleApp.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me){
                x = me.getX();
                y = me.getY();
            }
        });
        
        TitleApp.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent me){
                fram.setLocation(me.getXOnScreen() - x, me.getYOnScreen() - y);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleApp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listMenu1 = new swing.listMenu<>();

        TitleApp.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/img/162.png"))); // NOI18N
        jLabel1.setText("Gestion d'Entreprise");

        javax.swing.GroupLayout TitleAppLayout = new javax.swing.GroupLayout(TitleApp);
        TitleApp.setLayout(TitleAppLayout);
        TitleAppLayout.setHorizontalGroup(
            TitleAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleAppLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
        );
        TitleAppLayout.setVerticalGroup(
            TitleAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleAppLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitleApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TitleApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 1390, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    protected void paintChildren(Graphics grph){
        Graphics2D g2 = (Graphics2D) grph;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0,0,Color.decode("#353a42"),0,getHeight(),Color.decode("#000c2"));
        g2.setPaint(g);
        g2.fillRoundRect(0,0, getWidth(),getHeight(),15,15);
        g2.fillRect(getWidth() - 20,0,getWidth(),getHeight());
        super.paintChildren(grph);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TitleApp;
    private javax.swing.JLabel jLabel1;
    private swing.listMenu<String> listMenu1;
    // End of variables declaration//GEN-END:variables
}
