/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package page;

import Component.csvWriter;
import control.Main;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import model.model_inv;
import swing.scrollbar;

/**
 *
 * @author home
 */
public class inventaire extends javax.swing.JPanel {

    /**
     * Creates new form inventaire
     */
    private static int id = 0;
    
    public inventaire() {
        initComponents();
        numInventaire.setText("Inventaire - "+(Main.db.getNbrInv()+1));
        jScrollPane1.setBorder(new EmptyBorder(0,0,0,0));
        tableInv1.Update(benefice, total);
        jScrollPane1.getVerticalScrollBar().setUI(new scrollbar(false));
        jLabel1.setText("nombre : "+id);
        add.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent me){
                tableInv1.add(new Object[]{++id});
                jLabel1.setText("nombre : "+id);
            }
        });
        remove.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent me){
                if(id <= 0){
                    System.out.println("Ajouter d'abord des lignes");
                }else{
                    tableInv1.removeR(--id);
                    jLabel1.setText("nombre : "+id);
                }
            }
        });
        
        ecriture.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent me){
                if(date1.check() && !tableInv1.getList().isEmpty()){
                    csvWriter csv = new csvWriter();
                    try {
                        csv.writeThis(tableInv1.getList(), date1.getDate(), 7, numInventaire.getText());
                    } catch (IOException ex) {
                        Logger.getLogger(inventaire.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    makeMessage();
                }
            }
        });
        enregistrement.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent me){
                if(date1.check() && !tableInv1.getList().isEmpty() && !exec.getText().isEmpty()){
                    id = 0;
                    Main.db.insertInv(numInventaire.getText(), tableInv1.getTotal(), tableInv1.getBenef(), date1.getDate(), exec.getText());
                    csvWriter csv = new csvWriter();
                    try {
                        csv.writeThis(tableInv1.getList(), date1.getDate(), 7, numInventaire.getText());
                    } catch (IOException ex) {
                        Logger.getLogger(inventaire.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Main.instance.getGinv().addlast(new model_inv(numInventaire.getText(), tableInv1.getTotal(), tableInv1.getBenef(),exec.getText(),date1.getDate()));
                    Main.instance.redirection(9,"");
                }else{
                    makeMessage();
                }
            }
        });
        
        System.out.println(System.getProperty("user.dir"));
    }
    
    private void makeMessage(){
        warn.setEnabled(true);
        JOptionPane.showMessageDialog(this, "veuillez bien remplir la date et les champs du tableau", "Info", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new swing.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInv1 = new swing.tableInv();
        add = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        remove = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        benefice = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        ecriture = new swing.buttonV();
        enregistrement = new swing.buttonV();
        warn = new javax.swing.JLabel();
        panelBorder2 = new swing.PanelBorder();
        numInventaire = new javax.swing.JLabel();
        panelBorder3 = new swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        date1 = new model.date();
        exec = new javax.swing.JTextField();

        setBackground(new java.awt.Color(198, 208, 251));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        tableInv1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nom", "Type", "Prix Unitaire", "Prix de vente", "Nombre", "Benefice %", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableInv1);

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/img/icon/g1.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N
        jLabel3.setText("La somme total des marchandises hors benefice / perte : ");

        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/img/icon/g10.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N
        jLabel2.setText("La somme total des benefices : ");

        benefice.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        benefice.setForeground(new java.awt.Color(102, 102, 0));
        benefice.setText("01245");

        total.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(102, 102, 0));
        total.setText("0124");

        ecriture.setForeground(new java.awt.Color(255, 255, 255));
        ecriture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ecriture.setText("Ecrire en CSV");

        enregistrement.setForeground(new java.awt.Color(255, 255, 255));
        enregistrement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enregistrement.setText("Enregistrer");

        warn.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        warn.setForeground(new java.awt.Color(255, 0, 0));
        warn.setText("Veuillez ne pas ajouter une ligne vide, remplissez tous les champs et n'oubliez pas de mettre une date");
        warn.setEnabled(false);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1355, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(benefice))
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(total)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ecriture, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(enregistrement, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(warn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(remove)
                .addGap(16, 16, 16))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add)
                    .addComponent(remove)
                    .addComponent(warn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(total))
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(benefice))
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enregistrement, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(ecriture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));

        numInventaire.setBackground(new java.awt.Color(255, 204, 0));
        numInventaire.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        numInventaire.setForeground(new java.awt.Color(102, 102, 102));
        numInventaire.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numInventaire.setText("    numero d'inventaire");

        panelBorder3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("nbr : 10");

        javax.swing.GroupLayout panelBorder3Layout = new javax.swing.GroupLayout(panelBorder3);
        panelBorder3.setLayout(panelBorder3Layout);
        panelBorder3Layout.setHorizontalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorder3Layout.setVerticalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        date1.setBackground(new java.awt.Color(0, 51, 153));

        exec.setBackground(new java.awt.Color(255, 255, 255));
        exec.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        exec.setForeground(new java.awt.Color(102, 102, 102));
        exec.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Executeur", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addComponent(numInventaire, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exec, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numInventaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelBorder3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exec))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel benefice;
    private model.date date1;
    private swing.buttonV ecriture;
    private swing.buttonV enregistrement;
    private javax.swing.JTextField exec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numInventaire;
    private swing.PanelBorder panelBorder1;
    private swing.PanelBorder panelBorder2;
    private swing.PanelBorder panelBorder3;
    private javax.swing.JLabel remove;
    private swing.tableInv tableInv1;
    private javax.swing.JLabel total;
    private javax.swing.JLabel warn;
    // End of variables declaration//GEN-END:variables
}
